name: Deploy to EC2

on:
  push:
    branches:
      - main  # or the branch you want to watch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H YOUR.EC2.IP.ADDRESS >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@ec2-34-214-97-142.us-west-2.computer.amazonaws.com 'bash /home/ubuntu/my-app/deploy.sh'
