name: Deploy to EC2

on:
  push:
    branches:
      - main  # or the branch you want to watch

env:
  EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo $EC2_SSH_KEY > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan -H 44.246.103.39 >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@ec2-44-246-103-39.us-west-2.compute.amazonaws.com 'bash /home/ec2-user/deploy.sh'
